from typing import List, Optional
from pydantic import BaseModel, Field

class Source(BaseModel):
    """Schema representing a source with an URL."""
    url: str = Field(None, description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema representing the response from an agent."""
    answer: str = Field(..., description="The answer generated by the agent")
    sources: List[Source] = Field(
        default_factory=list, description="List of sources used to generate the answer"
    )